function createFallbackMessage(toolKey) {
  return `AI provider is temporarily unavailable for ${toolKey}. Generated a resilient fallback response.`;
}

function normalizeAiResult({ toolKey, toolTitle, result, providerKey, fallbackUsed, meta = {} }) {
  const base = result && typeof result === 'object' ? result : {};
  return {
    toolKey,
    toolTitle: toolTitle || toolKey,
    result: {
      title: base.title || toolTitle || toolKey,
      badges: Array.isArray(base.badges) ? base.badges : [],
      keyTakeaway: base.keyTakeaway || 'Generated by College OS AI Gateway.',
      sections: Array.isArray(base.sections) ? base.sections : [],
      followUps: Array.isArray(base.followUps) ? base.followUps : [],
      warnings: Array.isArray(base.warnings) ? base.warnings : []
    },
    meta,
    aiMeta: {
      provider: providerKey,
      fallbackActive: Boolean(fallbackUsed)
    }
  };
}

module.exports = {
  createFallbackMessage,
  normalizeAiResult
};
